import type { Project, ProjectCategory } from './types';

export const PROJECT_FILTERS: Array<'All' | ProjectCategory> = [
  'All',
  'Real-time Games',
  'Platforms',
  'Mobile',
  'Experiments',
];

export const PROJECTS: Project[] = [
  {
    id: 'rummy3plus',
    title: '3+ Rummy — Multiplayer Engine',
    category: 'Real-time Games',
    years: '2021 — 2024',
    org: 'Artoon Solutions',
    img: { src: '/assets/img/rummy3plus.jpg', alt: '3+ Rummy multiplayer engine', width: 1734, height: 1080 },
    blurb:
      'Point, pool and deal rummy on one authoritative engine — the core that went on to power eleven more white-label platforms.',
    metric: '12 platforms',
    metricLabel: 'White-label launches from one standardized core engine',
    details: [
      'Built the table lifecycle end to end: seat allocation, turn timers, draw/discard validation, declare and bet settlement.',
      'Live game state held in Redis and match history in MongoDB, so a player who dropped mid-hand could rejoin the same hand instead of forfeiting.',
      'Socket.IO room topology per table, with reconnection replay so returning clients resync to the exact turn state.',
      'Standardized the engine so a new white-label platform could be configured rather than rebuilt — launch time fell from weeks to days.',
    ],
    stack: ['Node.js', 'TypeScript', 'Socket.IO', 'Redis', 'MongoDB', 'Express'],
    links: [{ label: '3+ Rummy platform', url: 'https://3plusgames.com/' }],
  },
  {
    id: 'hyze',
    title: 'Hyze — On-Demand Mobility',
    category: 'Mobile',
    years: '2024 — 2025',
    org: 'Elluminati Inc',
    glyph: 'HYZE',
    glyphLabel: 'Live on Google Play',
    chips: ['Node.js', 'Socket.IO', 'Redis', 'MongoDB'],
    blurb:
      'Uber-style ride-hailing backend: trip lifecycle, live driver tracking, in-app chat and a multi-channel notification pipeline.',
    metric: '10,000+',
    metricLabel: 'Concurrent trips carried at peak across Socket.IO rooms',
    details: [
      'Built the backend for the full trip lifecycle — request, match, accept, en route, in progress, complete — with live driver location streaming throughout.',
      'Optimized driver geo-state modeling in Redis for low-latency nearest-driver lookups, and scaled Socket.IO rooms to 10,000+ concurrent trips at peak.',
      'Shipped in-app rider–driver chat plus a notification system spanning push, SMS and email.',
      'Designed and documented the REST API consumed by three clients: rider app, driver app and admin panel.',
    ],
    stack: ['Node.js', 'Express', 'TypeScript', 'Socket.IO', 'Redis', 'MongoDB', 'AWS SNS/SES'],
    links: [
      { label: 'Hyze on Google Play', url: 'https://play.google.com/store/search?q=hyze&c=apps' },
    ],
  },
  {
    id: 'wal',
    title: 'WAL — Freight Operations',
    category: 'Platforms',
    years: '2025',
    org: 'Logistic Infotech',
    glyph: 'WAL',
    glyphLabel: 'Freight ops · production',
    chips: ['React.js', 'Sails.js', 'MySQL', 'Socket.IO'],
    blurb:
      'Quotes, Orders, Carriers and Customer Management as connected modules — built end to end, front end to database.',
    metric: '40% faster',
    metricLabel: 'Quote turnaround after the carrier-selection redesign',
    details: [
      'Built the platform end to end — Quotes, Orders, Carriers and Customer Management as connected modules — React front end on a Sails.js / MySQL backend.',
      'Architected a carrier-selection flow that ranks carriers on rate and availability, cutting quote turnaround time by 40%.',
      'Engineered live shipment tracking with Socket.IO so operations staff and customers see the same state at the same moment.',
    ],
    stack: ['React.js', 'Node.js', 'Sails.js', 'TypeScript', 'Socket.IO', 'MySQL', 'PostgreSQL', 'Redis'],
    links: [],
  },
  {
    id: 'artoonmgp',
    title: 'Artoon MGP Rummy',
    category: 'Real-time Games',
    years: '2021 — 2024',
    org: 'Artoon Solutions',
    img: { src: '/assets/img/artoon-mgp.jpg', alt: 'Artoon MGP Rummy platform', width: 1192, height: 609 },
    blurb:
      'Multi-game platform skin of the rummy engine, packaged and configured for white-label clients.',
    metric: 'Weeks → days',
    metricLabel: 'New-platform launch time after engine standardization',
    details: [
      'Packaged the core engine as a configurable multi-game platform — stakes, timers, rake and table sizes as client configuration.',
      'Shipped MultiTable Rummy so a player could hold concurrent seats across tables without state collisions.',
      'Kept per-client rules isolated from the shared codebase so a fix in the core reached every platform at once.',
    ],
    stack: ['Node.js', 'TypeScript', 'Socket.IO', 'Redis', 'MongoDB'],
    links: [{ label: 'Artoon Solutions', url: 'https://artoonsolutions.com/' }],
  },
  {
    id: 'team18',
    title: 'Team-18 MGP Rummy',
    category: 'Real-time Games',
    years: '2021 — 2024',
    org: 'Artoon Solutions',
    img: { src: '/assets/img/team18-rummy.jpg', alt: 'Team-18 MGP Rummy platform', width: 1459, height: 690 },
    blurb:
      'A second white-label deployment of the multi-game platform, live with its own economy and skin.',
    details: [
      'Deployed the shared rummy core against a separate client economy, wallet and tournament configuration.',
      'Tuned turn-timer and reconnection windows for the client’s traffic profile and network conditions.',
      'Instrumented table events so operations could trace any hand from deal to settlement.',
    ],
    stack: ['Node.js', 'TypeScript', 'Socket.IO', 'Redis', 'MongoDB'],
    links: [],
  },
  {
    id: 'callbreak',
    title: 'CallBreak, Teen Patti & Roulette',
    category: 'Real-time Games',
    years: '2021 — 2024',
    org: 'Artoon Solutions',
    img: { src: '/assets/img/callbreak.jpg', alt: 'CallBreak, Teen Patti and Roulette games', width: 870, height: 967 },
    blurb: 'Trick-taking, betting and wheel games sharing the same real-time backend primitives.',
    details: [
      'Extended the engine beyond rummy: trick evaluation for CallBreak, blind/seen betting rounds for Teen Patti, timed spin settlement for Roulette.',
      'Reused the common layer — table lifecycle, turn timers, mid-hand reconnection, bet settlement — across every title.',
      'Kept authoritative state server-side so clients could never drive the outcome of a round.',
    ],
    stack: ['Node.js', 'TypeScript', 'Socket.IO', 'Redis', 'MongoDB'],
    links: [],
  },
  {
    id: 'ttt',
    title: 'Real-time Tic-Tac-Toe',
    category: 'Experiments',
    years: '2024',
    org: 'Personal project',
    img: { src: '/assets/img/tictactoe.jpg', alt: 'Real-time Tic-Tac-Toe game', width: 1080, height: 2340 },
    blurb:
      'A low-latency two-player engine — an excuse to push FastAPI, Socket.IO and BullMQ together.',
    details: [
      'Engineered a low-latency game engine on FastAPI with Socket.IO handling real-time state between the two players.',
      'Redis for data persistence and BullMQ for task scheduling — turn expiry, cleanup and match resolution.',
      'Responsive React front end with Material-UI, Lottie animations and Redux Toolkit for state.',
    ],
    stack: ['FastAPI', 'Python', 'Socket.IO', 'Redis', 'BullMQ', 'React.js', 'Redux Toolkit', 'MUI'],
    links: [
      {
        label: 'Walkthrough on LinkedIn',
        url: 'https://www.linkedin.com/in/vijay-parmar-00467b2b8/',
      },
    ],
  },
  {
    id: 'skillwinz',
    title: 'Skillwinz & Rummy Challenge',
    category: 'Real-time Games',
    years: '2021 — 2024',
    org: 'Artoon Solutions',
    glyph: 'SKILL–WINZ',
    glyphLabel: 'White-label · live',
    chips: ['TypeScript', 'Socket.IO', 'Redis', 'MongoDB'],
    blurb:
      'Two further production skins of the rummy engine, each with its own branding and tournament rules.',
    details: [
      'Configured and launched two additional white-label platforms on the standardized core.',
      'Validated the engine’s multi-tenant assumptions under separate live traffic and payout rules.',
      'Fed production issues from each skin back into the shared core so every platform improved at once.',
    ],
    stack: ['Node.js', 'TypeScript', 'Socket.IO', 'Redis', 'MongoDB'],
    links: [],
  },
  {
    id: 'slots',
    title: 'Slot Booking Platform',
    category: 'Platforms',
    years: 'In development',
    org: 'Personal project',
    glyph: 'SLOTS',
    glyphLabel: 'Active development',
    chips: ['Expo RN', 'Next.js', 'PostgreSQL', 'AWS'],
    blurb:
      'Cross-platform booking product: React Native app, Next.js web front end, one Node backend on AWS.',
    details: [
      'Expo React Native app for iOS and Android alongside a Next.js web front end, sharing one Express / TypeScript API.',
      'GPS-based location resolution to surface the right venues and slots for where the user actually is.',
      'Notification pipeline on AWS SNS and SES, PostgreSQL for relational booking data and MongoDB for flexible venue documents.',
    ],
    stack: ['Expo React Native', 'Next.js', 'Express', 'TypeScript', 'PostgreSQL', 'MongoDB', 'AWS'],
    links: [],
  },
];
